services:
  - type: web
    name: bookstore-api
    runtime: python
    plan: free
    rootDir: bookstore-frontend/bookstore_backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn bookstore_backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: CHAPA_SECRET_KEY
        sync: false
      - key: CHAPA_BASE_URL
        value: https://api.chapa.co
      - key: CHAPA_VERIFY_URL
        value: https://api.chapa.co/v1/transaction/verify/
      - key: CHAPA_RETURN_URL
        sync: false
      - key: CHAPA_CALLBACK_URL
        sync: false
