# Generated by Django 4.2.7 on 2026-05-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_options_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='merchant_reply',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='review',
            name='merchant_reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
